[package]
name = "test-parachain-adder"
version = "0.9.12"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which adds to a number as its state transition"
edition = "2018"
build = "build.rs"

[dependencies]
parachain = { package = "polkadot-parachain", path = "../../", default-features = false, features = [ "wasm-api" ] }
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a9465729e2c5d2ef8d87ac404da27e5e10adde8a" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.2", features = [ "global" ] }

# We need to make sure the global allocator is disabled until we have support of full substrate externalities
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, features = [ "disable_allocator" ] , rev = "a9465729e2c5d2ef8d87ac404da27e5e10adde8a" }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", rev = "a9465729e2c5d2ef8d87ac404da27e5e10adde8a" }

[features]
default = [ "std" ]
std = [
	"parachain/std",
	"sp-std/std",
]
